### ISSUE TITLE
Allot in installation time

### ISSUE THREAD

**Issue by emdupre** [jbpoline/computational-neuro-week1#2]
https://github.com/illdopejake/computational-neuro-week1/pull/1

**Comment by emdupre** [comment]
The full file: https://github.com/illdopejake/computational-neuro-week1/blob/e6ebba0a9737c37b43a6c4f698f61f435eadeb63/neuro-data-science.md

**Comment by jbpoline** [comment]
We should have installation time at the top

**Comment by emdupre** [comment]
I think this can be closed with #4 !
